-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 29, 2020 at 12:48 AM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.2.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `autonomy`
--

-- --------------------------------------------------------

--
-- Table structure for table `autobot`
--

CREATE TABLE `autobot` (
  `id` int(20) NOT NULL,
  `Name` varchar(50) DEFAULT NULL,
  `Description` varchar(2000) DEFAULT NULL,
  `img_path` varchar(25) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `autobot`
--

INSERT INTO `autobot` (`id`, `Name`, `Description`, `img_path`) VALUES
(1, 'Anterior talar articular surface', 'The anterior talar artciular surface of the calcaneus bone is located underneath the head of the talus. It helps to form the talocalcaneonavicular joint.', 'Anatomy_img/A/1.png'),
(2, 'Antitragus', 'The antitragus is a smaller projection posterior to the tragus and separated by the intertragic notch.', 'Anatomy_img/A/2.png'),
(3, 'Anterior inferior spine', 'This blunt anteriorly projecting spine is separated from the anterior superior spine by a shallow notch in the anterior iliac margin. The apex of this landmark is the attachment site of the straight tendon of the rectus femoris muscle. Its inferior surface provides attachment for the iliofemoral ligament.', 'Anatomy_img/A/3.png'),
(4, 'Articular facet for fibula', 'This is a small oval facet on the posterolateral aspect of the lateral tibial condyle. It faces distally where it receives the articular surface on the head of the fibula. Just superior to this the condyle is grooved for the tendon of the popliteus muscle.', 'Anatomy_img/A/4.png'),
(5, 'Acromial end', 'The laterally directed acromial end or extremity presents as a superior to inferior flattened surface articulating with the acromion of the scapula. One can palpate this landmark by touching the anterior aspect of the bony tip or peak of the shoulder.', 'Anatomy_img/A/5.png'),
(6, 'Articular fovea', 'This is the shallow, smooth articular surface at the proximal end of the radius. It articulates with the capitulum of the humerus.', 'Anatomy_img/A/6.png'),
(7, 'Accessory process of lumbar vertebra 1', 'This is a small projection from the posterior base of the transverse (costal) process. This, in combination with the mammillary process, forms the true transverse process that is homologous with the transverse processes of the thoracic region. It is a muscle attachment site, like all true transverse processes, for epaxial muscles.', 'Anatomy_img/A/7.png'),
(8, 'Auricular surface of the sacrum', 'The auricular surface is the ear-shaped, smooth surface on the lateral aspect of the sacral ala. It is covered with hyaline cartilage and forms a synovial joint with the corresponding surface on the iliac portion of the os coxa.', 'Anatomy_img/A/8.png'),
(9, 'Angle of rib 2', 'This is the proximal most part of the costal body. It is called the angle because of the sharp curve it forms with the junction of the neck. It provides surface for various muscle attachments.', 'Anatomy_img/A/9.png'),
(10, 'Angle of rib 5', 'This is the proximal most part of the costal body. It is called the angle because of the sharp curve it forms with the junction of the neck. It provides surface for various muscle attachments.', 'Anatomy_img/A/10.png'),
(11, 'Bones of the foot', 'The proximal end of the foot is the tarsus or ankle. The tarsal bones are seven in number and decrease in size from proximal to distal. Distal to the tarsus are the five digital rays. The four lateral digits consist of a metatarsal bone and three phalanges. The large medial digit, the hallux, has a metatarsal bone and only two phalanges.', 'Anatomy_img/B/1.png'),
(12, 'Base of metatarsal 4', 'Other Terms: Proximal end of metatarsal bone, Upper end of metatarsal bone, Base of metatarsal bone, Basis ossis metatarsi', 'Anatomy_img/B/2.png'),
(13, 'Body of the talus', 'The body is the block-like main portion of the bone covered by articular surfaces superiorly, inferiorly, and medially for articulations with the tibia, fibula, and calcaneus.', 'Anatomy_img/B/3.png'),
(14, 'Base of metatarsal 5', 'The base of the bone is the expanded, quadrate-shaped, proximal end.', 'Anatomy_img/B/4.png'),
(15, 'Base of metatarsal 1', 'The base of the bone is the expanded, quadrate-shaped proximal end. This end of the bone articulates with the medial cuneiform at its proximal surface.', 'Anatomy_img/B/5.png'),
(16, 'Base of the patella', 'The thick, convex superior border of the bone is the base. The rectus femoris and vastus intermedius muscles attach to this portion of the bone.', 'Anatomy_img/B/6.png'),
(17, 'Base of metatarsal 2', 'The base of the bone is the expanded, quadrate-shaped, proximal end.', 'Anatomy_img/B/7.png'),
(18, 'Body of the ilium', 'The body forms the thickened base of the ilium. Its external surface contributes to the upper two-fifths of the acetabulum. The upper part of this surface is smooth, contributing to the lunar articular surface with the femur. The lower portion of this surface is rough, contributing to the acetabular fossa in the central portion of the cup. The internal surface of the body contributes to the lateral wall of the true pelvis and provides attachment for the obturator internus muscle.', 'Anatomy_img/B/8.png'),
(19, 'Boney labyrinth', 'The boney labyrinth is the bony housing of the internal ear. It consists of the vestibule, semicircular canals, and the cochlea.', 'Anatomy_img/B/9.png'),
(20, 'Body of the ischium', 'The body forms the thick posterosuperior arm of the U-shaped ischium. Its external surface contributes to approximately one-half of the acetabulum forming the posterior lunar articular surface for the femur and the greater portion of the acetabular fossa. The internal surface contributes to the wall of the true or lesser pelvis, providing attachment for the obturator internus muscle. Its posterior margin forms the greater and lesser sciatic notches and ischial spine. Its postero-inferior surface is the rough ischial tuberosity.', 'Anatomy_img/B/10.png'),
(21, 'Calcaneus', 'Inspection of the calcaneus reveals an irregular shaped rectangular cube with its long axis similar to the long axis of the foot. Its distal face forms a small, smooth articular surface. Its posterior or proximal face forms a roughened calcaneal tubercle. The dorsal face forms wide, smooth articular surfaces anteriorly becoming rough and narrowed posteriorly. Both plantar and lateral faces are rough and flattened. The medial face presents as a shallow hollow.', 'Anatomy_img/C/1.png'),
(22, 'Ciliary body', 'The ciliary body is the middle layer situated between the retina and the sclera. It is thin and vascular. It is composed of ciliary muscle and zonular fibers. The zonular fibers hook the ciliary muscles to the lens. Zonular fibers are thin collagen fibers. Ciliary muscles are composed of smooth muscle. The ciliary body is coated by ciliary epithelium which produces aqueous humor. The inner transparent layer covers the vitreous body. The inner layer is unpigmented until it reaches the iris. The outer layer is pigmented. The ciliary body is portion of the uveal tract along with the iris, choroid of the eye, and the retina. The ciliary body receives innervation from the oculomotor nerve.', 'Anatomy_img/C/2.png'),
(23, 'Calcaneal tuberosity', 'This is the lump-like, posterior projection of the calcaneus called the heel. This serves as the attachment site of the triceps surae consisting of the gastrocnemius, soleus, and plantaris muscles.', 'Anatomy_img/C/3.png'),
(24, 'Calcaneal tubercle', 'This rounded protuberance at the distal end of the inferior calcanean surface is the distal site of attachment of the long plantar ligament.', 'Anatomy_img/C/4.png'),
(25, 'Cochlea', 'The cochlea bears resemblance to a snail shell. It is conical in form and placed almost horizontally in front of the vestibule. It forms the anterior part of the labyrinth. Its apex is directed anterior and lateralward, with a slight inclination inferior, toward the superior and anterior part of the labyrinth wall of the tympanic cavity. Its base corresponds with the inferior part of the internal acoustic meatus and is perforated by numerous apertures for the passage of the cochlear division of the acoustic nerve. It measures about five millimeters from base to apex Its breadth across the base is about nine millimeters. It consists of a conical shaped central axis, the modiolus, the bony canal, and the osseous spiral lamina. The basilar membrane stretches from the free border of its lamina to the outer wall of the bony cochlea and completely separates the canal into two passages. These passages communicate with each other at the apex of the modiolus by a small opening named the helicotrema. The modiolus is the conical central axis of the cochlea. ', 'Anatomy_img/C/5.png'),
(26, 'Cuboid', 'This is the lateral most and largest element in the distal row of the tarsal bones. As its name implies, the bone is cube-like, consisting of multiple flattened surfaces. Some of these surfaces are smooth, cartilage-covered, synovial joint faces and others are rough areas serving as sites for muscle and ligament attachment.', 'Anatomy_img/C/6.png'),
(27, 'Cornea', 'The cornea is the transparent window located at the front portion of the eye. It is the point at which the eye bulges. It covers the iris, pupil, and anterior chamber. The cornea refracts light. Unlike the lens, the corneas focus is fixed. It contributes most of the eyes focusing power.', 'Anatomy_img/C/7.png'),
(28, 'Choroid', 'The choroid is the middle vascular coat of the eye. It is located between the retina and the sclera. It is composed of loose connective tissue and is around .5 millimeters. The choroid delivers oxygen and nutrients to the outer layers of the retina. It is the greatest part of vascular tunic.', 'Anatomy_img/C/8.png'),
(29, 'Crest of the ilium', 'This is the upward arched superior border of the ilium separating the internal and external surfaces. The arch is not in a single plane, but follows a gradual sinuous curve. It ends anteriorly and posteriorly as the blunt anterior and posterior superior spines of the ilium. The highest point on the crest is level with a plane between the third and fourth lumbar spines. The crest can be divided into an internal lip, an intermediate region, and an external lip. These surfaces provide attachment for the lateral abdominal wall muscles, the quadratus lumborum, the latissimus dorsi, the iliocostalis, the gluteus maximus, and the tensor fasciae latae.', 'Anatomy_img/C/9.png'),
(30, 'Crest of the pubis', 'This is the top ridge of the pubic body medial to the tubercle. It is a rounded ridge providing attachment for the rectus abdominis and pyramidalis muscles and the inguinal falx.', 'Anatomy_img/C/10.png'),
(31, 'Distal phalan', 'These tiny bones form the pyramidal distal tip to the toes. The first one is much larger than the lateral four. Each forms a broad base for articulation with the phalanx proximal to it, a short tapering shaft, and an expanded end with a rough tuberosity on its plantar surface.', 'Anatomy_img/D/1.png'),
(32, 'Distal phalanges - hand', 'Like the metacarpal bones these bones are classified as having a proximal base, a narrowed shaft, and a distal head. These bones have reduced, flattened heads that do not form articular facets. The heads form a rough tuberosity on the palmar surface for attachment of the soft mass of the finger tips.', 'Anatomy_img/D/2.png'),
(33, 'Deciduous second molar - upper teeth', 'The second upper deciduous molar is a smaller replica of the upper first permanent molar. It, however, does not have a buccal cingulum that is as well developed as that of the first permanent molar. The roots diverge strongly from one another and tend to curve inward at their tips.', 'Anatomy_img/D/3.png'),
(34, 'Deltoid tuberosity', 'This forms a roughened, vertically oblong area on the lateral surface of the mid-humeral shaft. It serves as the attachment site for the deltoid muscle.', 'Anatomy_img/D/4.png'),
(35, 'Deciduous first molar - upper teeth', 'The upper first molar of the deciduous dentition resembles an intermediate stage between premolar and true molar. The buccal surface is tall medially, as a result of a well-developed buccal cingulum, and slopes to a lower prominence distally. A prominent lingual cingulum is also present. The lingual surface is typically narrower than the buccal surface and the occlusal surface has a quadrilateral shape. A deep groove divides the occlusal surface into distinct buccal and lingual sections. There are three roots flared roots that embrace the bud of the permanent tooth below.', 'Anatomy_img/D/5.png'),
(36, 'Dens or odontoid process', 'The dens is a conical, tooth-like projection from the superior surface of the axial body. It is approximately 1.5 centimeters long, having a broad base, narrowed central waist, and a tapering apex. The dens projects into the ring-like atlas where it serves as a pivotal axis for this bone.', 'Anatomy_img/D/6.png'),
(37, 'Deciduous canine - upper teeth', 'The maxillary deciduous canine has a short, wide, diamond-shaped crown, with a longer medial slope than distal slope. The labial surface of the tooth is convex and bulges near the neck. The lingual surface has a large cingulum with three longitudinal ridges projecting towards the occlusal surface. It has a narrow neck and a robust root that is triangular in cross section.', 'Anatomy_img/D/7.png'),
(38, 'Deciduous second molar - lower teeth', 'The crown of this tooth is very similar, but of smaller dimension, than the first permanent molar of the mandibular tooth row. It differs in having a much less prominent buccal cingulum, a much narrower neck, and greater initial divergence of the roots. Like in its upper counterpart, the roots tend to curve inward around the developing bud of its permanent replacement.', 'Anatomy_img/D/8.png'),
(39, ' Deciduous first molar - lower teeth', 'The mandibular deciduous first molar is interesting in its resemblance to a transitional stage between primitive and present hominid molariform teeth. In buccal view, the crown has two unequal parts, each supporting a cusp, separated by a faint buccal groove. The medial part is the more prominent. On the buccal surface is a large cingulum projecting mesially. The lingual surface is much more narrow than the buccal surface. The occlusal surface is oval in form with a thick distal border that tapers to a narrow mesiobuccal border. A ragged groove divides the occlusal surface into buccal and lingual halves. There are prominent raised cusps on the occlusal surface. The medial root is longer than the distal root.', 'Anatomy_img/D/9.png'),
(40, 'Deciduous canine - lower teeth', 'The lower deciduous canine is more slender than its counterpart in the upper jaw. In labial view it has an elongated diamond-shape appearance and it is much thinner in labiolingual diameter. Its lingual surface has a reduced cingulum with less prominent marginal ridges than the upper canine. The distal slope of the cusp is longer than the mesial slope of the cusp. It has a single pointed root.', 'Anatomy_img/D/10.png'),
(41, 'Eyeball', 'The eyeball is almost spherical, but not perfectly so, mainly because its anterior, clear, or corneal segment has a greater curvature than the rest of the eye. Considering it as a globe, it has an anterior pole and a posterior pole; the former corresponding to the center of the front of the cornea, the latter to the center of the posterior curvature. An imaginary straight line joining, the two poles is called the axis of the eyeball. The equator of the eye is that part of its surface which lies midway between the two poles. The optic nerve joins the globe three or four mm to the nasal side of the posterior pole. The shape of the eye depends on, and is preserved by, the outermost tunic, formed conjointly by the cornea and sclera. All around the cornea there remains a little adherent conjunctiva; elsewhere, the sclera is directly exposed, except for some loose connective tissue which adheres to it, especially around the optic nerve entrance. In front of the equator we see the tendinous insertions of the four recti muscles. Behind the equator are the insertions of the two oblique muscles-that of the superior oblique tendinous, and further forward, under the superior rectus; that of the inferior more fleshy, and placed between the optic nerve and the lateral rectus.', 'Anatomy_img/E/1.png'),
(42, 'Ethmoid', 'It is an unpaired bone wedged between the right and left orbits of the skull. The bone consists of a median vertical plate, a horizontal plate perforated by many small foramina, and bilateral pneumatic labyrinthine regions. The labyrinthine regions form most of the medial walls of the orbit and the superior and middle nasal conchae. This bone consists of thin laminae of compact bone surrounding many small air sinuses. These sinuses have mucous membranes that are continuous through openings and channels with the nasal mucosa. The thickest portion of the bone, the crista galli, is the superior projection of the perpendicular plate above the horizontal cribriform plate.', 'Anatomy_img/E/2.png'),
(43, 'Ethmoidal air cells', 'The ethmoidal air cells are small osseous sinuses located between the thin orbital and nasal plates of the ethmoid bone. There are three groups – anterior, middle, and posterior – of air cells in the bone. They form a labyrinthine network of spaces and communicate with the meatuses of the nasal cavity. They begin to develop in utero and are small, narrow pouches at birth.', 'Anatomy_img/E/3.png'),
(44, 'Ethmoid bulla', 'The bulla is a swelling formed on the lateral wall of the middle meatus. This bulge is produced by the middle ethmoidal air cells. These air sinuses communicate with the meatus just superiorly to the bulla.', 'Anatomy_img/E/4.png'),
(45, 'External ear', '', 'Anatomy_img/E/5.png'),
(46, 'Ethmoidal notch', 'This is the rectangular notch making the posterior part of the nasal portion of the frontal bone incomplete. The cribriform plate of the ethmoid bone fills this notch and articulates at its borders.', 'Anatomy_img/E/6.png'),
(47, 'Endolymphatic duct', 'The endolymphatic duct runs off of the posterior wall of the saccule. It is joined by the utriculosaccular duct and then passes along the vestibular aqueduct and ends in a blind pouch termed the endolymphatic sac on the posterior surface of the petrous portion of the temporal bone.', 'Anatomy_img/E/7.png'),
(48, 'External aperture for vestibular aqueduct', 'This is a small slit in the bone situated on the broad posterior surface of the petrous temporal bone. This slit-like opening is often almost hidden by a thin, over-hanging plate of bone. It marks the opening into the vestibular aqueduct. The endolymphatic sac protrudes through this opening between the periosteum and the dura mater. Blood vessels also accompany the endolymphatic duct in this canal.', 'Anatomy_img/E/8.png'),
(49, 'External acoustic meatus', 'The external acoustic meatus is the passageway of the external ear that carries sound waves through the cartilage and temporal bone to the tympanic membrane (eardrum), or membranous lateral window of the tympanic cavity. Lining the meatus is a glandular integument. The glands are modified sebaceous glands, called ceruminous glands, which produce the wax of the ear canal.', 'Anatomy_img/E/9.png'),
(50, 'External aperture for cochlear canal', 'This small aperture sits on the rough inferior surface of the petrous temporal bone. It is a round opening to the cochlear canaliculus situated inferiorly to the internal acoustic meatus, medial to the carotid foramen, and anterior to the jugular fossa. It transmits the perilymphatic duct into the internal ear, along with a tube of dura mater and a vein from the cochlea to the internal jugular vein.', 'Anatomy_img/E/10.png'),
(51, 'Facet for lateral malleolus', 'This is a large, somewhat triangular facet covering most of the lateral surface of the talus. It functions as the articular surface for the fibular malleolus.', 'Anatomy_img/F/1.png'),
(52, 'Fovea dentis', 'This fovea is a small, smooth circular area on the internal surface of the anterior arch. This is the articular surface for the dens of the axis.', 'Anatomy_img/F/2.png'),
(53, 'Foramen lacerum', 'The foramen lacerum is variably sized gap with three borders. Its anterior border is the sphenoidal body at the junction of the greater wing and pterygoid process. The posterior border is the medial end of the petrous temporal bone. The medial border is the basioccipital bone. It is filled by connective tissue in life and transmits the small meningeal branches of the ascending pharyngeal artery and emissary veins from the cavernous sinus.', 'Anatomy_img/F/3.png'),
(54, 'Facet for medial malleolus', 'This facet is a small, lunar-shaped surface on the superomedial aspect of the talus for articulation with the tibial malleolus.', 'Anatomy_img/F/4.png'),
(55, 'First coccygeal vertebra', 'This is one of three to five vertebral segments, most commonly from four, that fuse to form the coccyx. The first segment is characteristic of the vertebral plan, with succeeding segments becoming highly reduced. The first segment has small costotransverse processes. It also has superior projecting cornua that represent modified pedicles and superior articular processes. The superior surface of the first segment\'s body forms an oval articular surface with the inferior surface of the fifth sacral segment. The bone provides attachment for the gluteus maximus, levator ani, external anal sphincter, coccygeus, and various coccygeal ligaments.', 'Anatomy_img/F/5.png'),
(56, 'First molar - upper teeth', 'The first and second resemble each other so closely that one description will serve for the two. The grinding surface is quadrilateral, with rounded angles. It has four cusps, two buccal and two lingual. Of these, the anterior lingual is the largest, and is connected with the posterior buccal by an oblique ridge of enamel. The groove separating the buccal and lingual cusps extends on to the sides of the crown and is lost near the neck. The median and distal borders usually present a slight ridge. The roots are three in number, two on the labial, and one on the palatine aspect; this last is usually referred to as the palatine root, and often diverges from the crown at a considerable angle.', 'Anatomy_img/F/6.png'),
(57, 'Femur', 'The femur is the largest and longest bone of the body. Its shaft forms a long cylindrical tube with a forward bow. It contains thick walls of compact bone surrounding a hollow medullary cavity. The strong wall is thickest near the narrow center of the shaft where the medullary cavity is also most spacious. As the shaft becomes progressively wider toward each end, the compact wall of bone becomes thinner and the medullary cavity accumulates spongy bone. The proximal end consists of a short cantilevered neck capped by a smooth, round articular head. Rounded projections of bone form at the base of the cantilevered neck. The distal end, consisting of two large, knuckle-like processes separated by an intermediate groove, is larger than the proximal end. In the standing position the femoral shaft angles obliquely from lateral to medial.', 'Anatomy_img/F/7.png'),
(58, 'Fourth coccygeal vertebra', 'This is one of three to five vertebral segments, most commonly from four, that fuse to form the coccyx. The first segment is characteristic of the vertebral plan, with succeeding segments becoming highly reduced. The first segment has small costotransverse processes. It also has superior projecting cornua that represent modified pedicles and superior articular processes. The superior surface of the first segment\'s body forms an oval articular surface with the inferior surface of the fifth sacral segment. The bone provides attachment for the gluteus maximus, levator ani, external anal sphincter, coccygeus, and various coccygeal ligaments.', 'Anatomy_img/F/8.png'),
(59, 'Fovea of head', 'The fovea is a shallow depression in the center of the articular surface of the head not covered by articular cartilage. The articular capsule folds along the edge of this pit. Connective tissue within the fold serves as a ligament for the head of the femur. Vessels supplying the head also traverse this ligamentous fold.', 'Anatomy_img/F/9.png'),
(60, 'Fifth coccygeal vertebra', 'This is one of three to five vertebral segments, most commonly from four, that fuse to form the coccyx. The first segment is characteristic of the vertebral plan, with succeeding segments becoming highly reduced. The first segment has small costotransverse processes. It also has superior projecting cornua that represent modified pedicles and superior articular processes. The superior surface of the first segment\'s body forms an oval articular surface with the inferior surface of the fifth sacral segment. The bone provides attachment for the gluteus maximus, levator ani, external anal sphincter, coccygeus, and various coccygeal ligaments.', 'Anatomy_img/F/10.png'),
(61, 'Groove for flexor hallucis longus of calcaneus', 'This groove, for the wide tendon of the flexor hallucis longus muscle, sits on the inferior surface of the sustentaculum tali. It is the continuation of the similar named groove on the posterior surface of the talus.', 'Anatomy_img/G/1.png'),
(62, 'Groove for popliteus', 'The groove sits on the posterior aspect of the lateral condyle, just behind and below the epicondyle. Its anterior aspect is the site of attachment for the popliteus muscle, while its posterior portion is a groove that receives the popliteus tendon during full flexion of the knee joint.', 'Anatomy_img/G/2.png'),
(63, 'Gonion', 'The gonion is the outer margin of the angle of the mandible.', 'Anatomy_img/G/3.png'),
(64, 'Groove for flexor hallucis longus of talus', 'This is the prominent groove between the two tubercles on the posterior process of the talus. Through the groove courses the strong tendon of the flexor hallucis longus muscle as it passes into the foot.', 'Anatomy_img/G/4.png'),
(65, 'Glenoid cavity', 'The cavity contributes to the lateral angle of the scapula. It is a shallow, pear-shaped surface for articulation with the humeral head. It is often called the head of the scapula.', 'Anatomy_img/G/5.png'),
(66, 'Groove for the fibularis longus tendon', 'This is an obliquely oriented groove situated distal to and paralleling the ridge-like tuberosity. Through it runs the peroneus longus tendon as it courses transversely across the plantar surface of the foot.', 'Anatomy_img/G/6.png'),
(67, 'Greater tubercle', 'This is the larger of two bump-like projections of the proximal humerus. It is situated lateral to the head and lesser tubercle. To it attach the supraspinatus, infraspinatus, and teres minor muscles.', 'Anatomy_img/G/7.png'),
(68, 'Greater sciatic notch', 'This is the large, deep notch on the posterior margin of the ischium, above the ischial spine and below the junction with the posterior inferior iliac spine. This notch provides passage to the piriformis muscle, the superior and inferior gluteal vessels and nerves, the sciatic and posterior femoral cutaneous nerves, the internal pudendal vessels and pudendal nerve, and the nerves to the obturator internus and quadratus femoris muscles on their course from the pelvis to the gluteal region.', 'Anatomy_img/G/8.png'),
(69, 'Groove for radial nerve', 'A shallow groove toward the lateral surface of the mid-humeral shaft. This descends laterally and anteriorly carrying the radial nerve distally.', 'Anatomy_img/G/9.png'),
(70, 'Greater trochanter', 'The greater trochanter is the knob-like lateral projection at the proximal end of the femur. It serves as the site of attachment for the gluteus minimus, gluteus medius, gluteus maximus, piriformis, obturator internus, superior and inferior gemellus, and obturator externus muscles.', 'Anatomy_img/G/10.png'),
(71, 'Head of talus', 'The smooth, convexly oval cap to the neck that articulates with the navicular bone.', 'Anatomy_img/H/1.png'),
(72, 'Head of metatarsal 4', 'The round, distal heads form the balls of the feet. The articular surface of the head is a rounded, convex surface that is more narrow transversely. The smooth articular surface spreads further onto the plantar surface than it does on the dorsal surface.', 'Anatomy_img/H/2.png'),
(73, 'Head of metacarpal 1', 'The round, distal heads form the large knuckle in the hand. The articular surface of the head is a rounded convex surface that is more narrow transversely. The smooth articular surface spreads further onto the palmar surface than it does on the dorsal surface.', 'Anatomy_img/H/3.png'),
(74, 'Head of metatarsal 1', 'The round, distal heads are large and prominent. The articular surface of the head is a rounded convex surface that is more narrow transversely. The smooth articular surface spreads further onto the plantar surface than it does on the dorsal surface. On the plantar surface, the head forms grooved facets for the sesamoid bones of the flexor hallucis brevis.', 'Anatomy_img/H/4.png'),
(75, 'Head of metatarsal 5', 'The round, distal heads form the balls of the feet. The articular surface of the head is a rounded, convex surface that is more narrow transversely. The smooth articular surface spreads further onto the plantar surface than it does on the dorsal surface.', 'Anatomy_img/H/5.png'),
(76, 'Head of metacarpal 2', 'The round, distal heads form the large knuckle in the hand. The articular surface of the head is a rounded convex surface that is more narrow transversely. The smooth articular surface spreads further onto the palmar surface than it does on the dorsal surface.', 'Anatomy_img/H/6.png'),
(77, 'Head of metatarsal 2', 'The round, distal heads form the balls of the feet. The articular surface of the head is a rounded, convex surface that is more narrow transversely. The smooth articular surface spreads further onto the plantar surface than it does on the dorsal surface.', 'Anatomy_img/H/7.png'),
(78, 'Head of femur', 'The head is the rounded proximal end of the femur capped with articular cartilage. It is the site of articulation with the acetabulum of the os coxa. This rounded epiphyseal center consists of a thin surrounding plate of compact bone over an inner spongy center.', 'Anatomy_img/H/8.png'),
(79, 'Head of fibula', 'The head is the moderately expanded proximal end of the fibula. It serves as the attachment site for the extensor digitorum longus, peroneus longus, soleus, and biceps femoris muscles. The fibular collateral and tibiofibular capsular ligaments also attach here. This landmark is easily palpated.', 'Anatomy_img/H/9.png'),
(80, 'Helix', 'The helix is the prominent rim of the auricle that forms the outer curve of this structure.', 'Anatomy_img/H/10.png'),
(81, 'Intermediate cuneiform', 'This is the smallest of the three cuneiform bones. Like the lateral cuneiform the broad base of the wedge-shaped bone faces dorsally. Its lateral, medial, distal, and proximal surfaces are all smooth, cartilage covered articular facets. The narrow plantar and broad dorsal surfaces are roughened for the attachment of strong interosseous ligaments.', 'Anatomy_img/I/1.png'),
(82, 'Internal labium', 'This term is applied to the internal edge of the iliac crest. It provides attachment for, from anterior to posterior, the transversus abdominis, quadratus lumborum, and iliocostalis muscles.', 'Anatomy_img/I/2.png'),
(83, 'Iris', 'The iris projects out into aqueous humor and divides it into chambers. It controls the diameter and size of the pupils and the amount of light that can actually reach the pupils. The iris is what gives the eye its color.', 'Anatomy_img/I/3.png'),
(84, 'Iliac Fossa', 'The iliac fossa is the smooth, shallow concavity on the internal surface of the ala forming the lateral wall of the false pelvis or lower abdomen. It is the attachment site of the iliacus muscle.', 'Anatomy_img/I/4.png'),
(85, 'Inferior gluteal line', 'This line on the external surface of the iliac ala is intermediate in length between the other two gluteal lines. It courses in an anteroposterior line from anterior inferior iliac spine to the greater sciatic notch. It defines the boundary between the attachment surfaces for the gluteus medius, above the line, and gluteus minimus, below the line.', 'Anatomy_img/I/5.png'),
(86, 'Internal acoustic meatus', 'The internal acoustic meatus is the passageway for the facial and vestibulocochlear nerves from the temporal bone to the middle cranial fossa.', 'Anatomy_img/I/6.png'),
(87, 'Iliac tuberosity', 'This is the rough surface of bone on the posterior sacropelvic surface of the iliac ala. It is bordered superiorly by the posterior iliac crest, anteriorly by the iliac fossa, and inferiorly by the auricular surface for the sacrum. It provides attachment for iliac ligaments and the multifidus muscle.', 'Anatomy_img/I/7.png'),
(88, 'Ilium', 'The body, the thick base of this bone, is a thick mass forming the superior portion of the acetabulum. Its upper margins are the arcuate line internally and the superior rim of the acetabulum externally. The ala radiates from the body as a fan-shaped plate of bone. The medial or sacropelvic surface is concave while the lateral or gluteal surface is slightly convex. The top of this expanded bone forms the arched crest terminating at both ends as the anterior superior and posterior superior spines. At the posterior end of the crest the internal surface becomes exceedingly rough providing attachment for the sacrum.', 'Anatomy_img/I/8.png'),
(89, 'Ischium', 'It is an arched or U-shaped element with its concave notched margin contributing to the posterior two-thirds of the obturator foramen. It is divisible into two parts, a more posterior positioned body forming the thickest part of the os coxa and a slender anterior ramus. The superior portion of the body is the greatest contributor of the three bones of the os coxa to the acetabulum. It forms the posterior portion of the lunar articular surface for the femur and forms almost the entire rough acetabular fossa. The ischium ossifies from a primary center that appears during the fourth month in the body of the ischium. Around the seventh year the pubis and ischium join to form an ossified ramus inferior to the obturator foramen. At puberty a secondary center appears in the ischial tuberosity. This secondary center joins with the primary center anywhere between the fifteenth and twenty-fifth year.', 'Anatomy_img/I/9.png'),
(90, 'Intermediate line', 'This is the region of the crest between the external and internal labia, in essence forming the ridge of the crest. It serves as the attachment site for the internal oblique muscle.', 'Anatomy_img/I/10.png'),
(91, 'Jugular notch of the sternum', 'This is the concave superior border of the manubrium. This is the thickest region of the bone.', 'Anatomy_img/J/1.png'),
(92, 'Jugular process', 'The jugular process is a rectangular plate of bone projecting from the posterior half of the occipital condyle. The rough inferior surface of this process provides attachment for the rectus capitis lateralis muscle and the lateral atlanto-occipital ligament.', 'Anatomy_img/J/2.png'),
(93, 'Joints and ligaments of the radius and ulna', 'The proximal end of the radius and ulna articulate within the structure of the elbow joint. This articular anatomy is covered with the elbow joint. Along the entire shaft of the radius and ulna, an interosseous membrane unites the two bones. This is a synarthrotic joint that functions both as a binding structure between the adjacent bones and also as a large surface area for muscle attachment. In addition to the interosseous membrane, a syndesmotic ligament, the oblique cord, also helps to bind the radius to the ulna. At the distal end of the antebrachial skeleton, the radius and ulna form a distal radio-ulnar joint. This is a pivot joint that is associated with the anatomy of the wrist capsule. The proximal and distal radio-ulnar joints participate in the movements of pronation and supination.', 'Anatomy_img/J/3.png'),
(94, 'Jugular foramen', 'The jugular foramen is the large gap formed between the jugular notch of the occipital bone and the posterior border of the petrous temporal bone. This passageway from the cranial vault transmits the internal jugular vein along with the vagus, glossopharyngeal, and accessory nerves.', 'Anatomy_img/J/4.png'),
(95, 'Jejunum', 'The jejunum\'s diameter is about four centimeters. It is thicker, more vascular, and of a deeper color than the ileum. The circular folds of its mucous membrane are large and thickly set. Its villi are larger than in the ileum. The aggregated lymph nodules are almost absent in the upper part of the jejunum. In the lower part, the lymph nodules are less frequently found than in the ileum and are smaller and tend to assume a circular form. The circular folds are absent in the lower part of the ileum. The jejunum mostly occupies the umbilical and left iliac regions. The jejunum and ileum are attaché to the posterior abdominal wall by mesentery. The mesentery allows the freest motion so that each coil can accommodate itself to changes in form and position.', 'Anatomy_img/J/5.png'),
(96, 'Joints and ligaments of the carpal bones', 'These are small joints with, in general, very limited ranges of motion that occur between the neighboring surfaces of adjacent carpal bones and between the distal ends of the carpal bones and the proximal ends of the metacarpal bones. The unique joint in this group is the carpometacarpal joint of the thumb, which unlike all the other joints in this group has a wide range of motion.', 'Anatomy_img/J/6.png'),
(97, 'Jugular notch of the temporal', 'This is a notch formed on the inferior margin of the petrous temporal bone\'s posterior surface. This notch is an impression left by the junction of the internal jugular vein and the sigmoid sinus. It combines with the corresponding notch of the occipital bone to form the jugular foramen.', 'Anatomy_img/J/7.png'),
(98, 'Jejunal arteries', 'The jejunal arteries originate in the superior mesenteric artery. They supply the jejunum. They anastomose with the ileal arteries.', 'Anatomy_img/J/8.png'),
(99, 'Joints and ligaments of the digits (hand)', 'These are the small, mobile joints that occur between the distal ends of the metacarpal bones and the proximal end of the proximal phalanges (metacarpophalangeal joints) and between adjacent phalanges (interphalangeal joints).', 'Anatomy_img/J/9.png'),
(100, 'Jugular fossa', 'This is a variable sized concavity on the rough inferior surface of the petrous temporal bone. It is posterior to the carotid foramen. This surface holds the bulbous portion of the internal jugular vein as it drains from the sigmoid venous sinus.', 'Anatomy_img/J/10.png'),
(101, 'Kidney', 'The kidneys are situated in the posterior part of the abdomen, one on either side of the vertebral column, behind the peritoneum, and surrounded by a mass of fat and loose connective tissue. Their upper extremities are on a level with the upper border of the twelfth thoracic vertebra, their lower extremities on a level with the third lumbar. The right kidney is usually slightly lower than the left, probably on account of the vicinity of the liver. The long axis of each kidney is directed inferior, and lateral; the transverse axis posterior and lateral. Each kidney is about 11.25 cm in length, 5 to 7.5 cm in breadth, and a little more than 2.5 cm in thickness. The left is somewhat longer, and narrower, than the right. The weight of the kidney in the adult male varies from 125 to 170 gm, in the adult female from 115 to 155 gm. The combined weight of the two kidneys in proportion to that of the body is about 1 to 240. The kidney has a characteristic form, and presents for examination two surfaces, two borders, and an upper and lower extremity.', 'Anatomy_img/K/1.png'),
(102, 'Knee joint and ligaments', 'The relationships between the femur and the tibia provide no interlocking joint mechanisms or stability between these neighboring bones and from this perspective the knee joint is completely unstable. That is, there are no deep-seated sockets or hinge-like grooves that limit and stabilize the movements of articulating bones. Instead, the knuckle-like ends of the femur sit on the flat plateau-like surface of the tibia. The strength of the knee joint is dependent on strong ligaments and surrounding muscles. Although its primary motions are of a hinge nature, it is a complex joint with subtle rotational and sliding movements also.', 'Anatomy_img/K/2.png'),
(103, 'Knee', 'The knee joint is the largest joint in the human body, and the joint most commonly affected by arthritis. Knowing about knee anatomy can help people understand how knee arthritis develops and sometimes causes pain.', 'Anatomy_img/K/3.png'),
(104, 'Knee region', 'region overlying the knee joint between the femoral region (thigh) proximally and leg distally; includes the anterior and posterior regions of the knee, the latter including the popliteal fossa.', 'Anatomy_img/K/4.png'),
(105, 'Lower limb - bones of', 'The broad base of the inferior limb is the pelvic girdle. This girdle is the strong fusion of three bones, the ilium, ischium, and pubis. It is firmly anchored to the axial skeleton via ligamentous attachments at the sacro-iliac joint. The bony framework of the next segment of the limb, the thigh, is the femur with the sesamoid patella at its distal end. Distal to the femur, the tibia and fibula form the skeleton of the leg. The distal most region of the inferior limb is the foot consisting of seven tarsal bones, five metatarsal bones, and fourteen phalanges.', 'Anatomy_img/L/1.png'),
(106, 'Lacrimal gland', 'In human physiology, the lacrimal glands are paired, almond-shaped exocrine glands, one for each eye, that secrete the aqueous layer of the tear film. They are situated in the upper lateral region of each orbit, in the lacrimal fossa of the orbit formed by the frontal bone.', 'Anatomy_img/L/2.png'),
(107, 'Lateral process of calcaneal tuberosity', 'The lateral process of the calcaneal tuberosity, small, prominent, and rounded, gives origin to part of the Abductor digiti quinti.', 'Anatomy_img/L/3.png'),
(108, 'Lacrimal papilla', 'The lacrimal papilla is the small rise in the bottom eyelid just before it ends at the corner of the eye closest to the nose. In the middle of it is the lacrimal punctum, a small hole that lets tears drain into the inside of the nose through the lacrimal canaliculi.', 'Anatomy_img/L/4.png'),
(109, 'Lateral process of the talus', 'The lateral process of the talus is a large, wedge-shaped osseous projection that extends laterally from the body of the talus. Its inferolateral surface comprises a portion of the posterior facet of the talocalcaneal joint, while its superolateral surface articulates with the lateral malleolus.', 'Anatomy_img/L/5.png'),
(110, 'Lacrimal sac', 'The lacrimal sac or lachrymal sac is the upper dilated end of the nasolacrimal duct, and is lodged in a deep groove formed by the lacrimal bone and frontal process of the maxilla.', 'Anatomy_img/L/6.png'),
(111, 'Lateral tubercle', 'Lateral process on the groove for tendon of flexor hallucis longus.', 'Anatomy_img/L/7.png'),
(112, 'Lobule of auricle', 'The lobule, the fleshy lower part of the auricle, is the only area of the outer ear that contains no cartilage. The auricle also has several small rudimentary muscles, which fasten it to the skull and scalp.', 'Anatomy_img/L/8.png'),
(113, 'Lateral cuneiform', 'The lateral cuneiform is a wedge-shaped bone. It is smaller than the medial cuneiform and larger than the intermediate cuneiform. It lies edge downward, between the intermediate cuneiform and cuboid.', 'Anatomy_img/L/9.png'),
(114, 'Lateral articular facet', 'The biomechanical function of each pair of facet joints is to guide and limit movement of the spinal motion segment. In the lumbar spine, for example, the facet joints function to protect the motion segment from anterior shear forces, excessive rotation and flexion. Facet joints appear to have little influence on the range of side bending (lateral flexion). These functions can be disrupted by degeneration, dislocation, fracture, injury, instability from trauma, osteoarthritis, and surgery. In the thoracic spine the facet joints function to restrain the amount of flexion and anterior translation of the corresponding vertebral segment and function to facilitate rotation. Cavitation of the synovial fluid within the facet joints is responsible for the popping sound (crepitus) associated with manual spinal manipulation, commonly referred to as \"cracking the back.\"', 'Anatomy_img/L/10.png'),
(115, 'Medial process of calcaneal tuberosity', 'The medial process of the calcaneal tuberosity, broader and larger, gives attachment, by its prominent medial margin, to the Abductor hallucis, and in front to the Flexor digitorum brevis and the plantar aponeurosis.', 'Anatomy_img/M/1.png'),
(116, 'Macula', 'The macula is the central area of the retina and is of particular interest to retina specialists. Remember, that the retina is the light. sensitive tissue which lines the inside of the eye. The macula is the functional center of the retina. It gives us the ability to see “20/20” and provides the best color vision.', 'Anatomy_img/M/2.png'),
(117, 'Middle talar articular surface', 'On the superior surface of the calcaneus, in front and to the medial side of the calcaneal sulcus is an elongated facet, concave from behind forward, and with its long axis directed forward and lateralward. This facet is frequently divided into two by a notch: of the two, the posterior, and larger is termed the middle talar articular surface; it is supported on a projecting process of bone, the sustentaculum tali, and articulates with the middle calcaneal facet on the under surface of the talus; the anterior talar articular surface is placed on the anterior part of the body, and articulates with the anterior calcaneal facet on the talus.', 'Anatomy_img/M/3.png'),
(118, 'Middle ear', 'he middle ear is the part of the ear between the eardrum and the oval window. The middle ear transmits sound from the outer ear to the inner ear. The middle ear consists of three bones: the hammer (malleus), the anvil (incus) and the stirrup (stapes), the oval window, the round window and the Eustrachian tube.', 'Anatomy_img/M/4.png'),
(119, 'Medial tubercle', 'Medial process of the groove for tendon of flexor hallucis longus.', 'Anatomy_img/M/5.png'),
(120, 'Mastoid antrum', 'The mastoid antrum (tympanic antrum, antrum mastoideum, Valsalva\'s antrum) is an air space in the petrous portion of the temporal bone, communicating posteriorly with the mastoid cells and anteriorly with the epitympanic recess of the middle ear via the aditus to mastoid antrum (entrance to the mastoid antrum). These air spaces function as sound receptors, provide voice resonance, act as acoustic insulation and dissipation, provide protection from physical damage and reduce the mass of the cranium.[citation needed] The roof is formed by the tegmen antri which is a continuation of the tegmen tympani and separates it from the middle cranial fossa. The lateral wall of the antrum is formed by a plate of bone which is an average of 1.5 cm in adults. The mastoid air cell system is a major contributor to middle ear inflammatory diseases.', 'Anatomy_img/M/6.png'),
(121, 'Medial cuneiform', 'The medial cuneiform (also known as first cuneiform) is the largest of the cuneiforms. It is situated at the medial side of the foot, anterior to the navicular bone and posterior to the base of the first metatarsal. Lateral to it is the intermediate cuneiform.', 'Anatomy_img/M/7.png'),
(122, 'Membranous labyrinth', 'The membranous labyrinth (latin: labyrinthus membranaceus) is a system of ducts and dilatations located within the bony labyrinth of the internal ear and it contains the receptors for hearing and balance. The membranous labyrinth is composed of two functional parts: the vestibular labyrinth and the cochlear labyrinth.', 'Anatomy_img/M/8.png'),
(123, 'Metatarsal 1', 'The first metatarsal bone is the bone in the foot just behind the big toe. The first metatarsal bone is the shortest of the metatarsal bones and by far the thickest and strongest of them.Like the four other metatarsals, it can be divided into three parts: base, body and head. The base is the part closest to the ankle and the head is closest to the big toe. The narrowed part in the middle is referred to as the body of the bone. The bone is somewhat flattened, giving it two sides: the plantar (towards the sole of the foot) and the dorsal side.', 'Anatomy_img/M/9.png'),
(124, 'Neck of talus', 'This landmark is the narrowed distal projection of the talar body. It has a rough surface texture perforated by many nutrient foramina. It serves as the attachment site for many talar ligaments.', 'Anatomy_img/N/1.png'),
(125, 'Navicular', 'This short, disc-like bone is positioned between the distal end of the talar head and the proximal end of the three cuneiform bones. Its proximal and distal surfaces present as flattened oval faces. The proximal surface forms a shallow oval concavity. The distal surface, being transversely convex, divides into three aspects that form articular surfaces with the three cuneiform bones. Dorsal, lateral, plantar, and medial surfaces form a rough circumference to the disk. The medial surface projects as a rounded tubercle while the lateral surface presents as a small, smooth articular surface. The dorsal surface is convex and the plantar surface concave.', 'Anatomy_img/N/2.png'),
(126, 'Neck of the femur', 'The neck is the cantilevered extension of the femoral shaft capped by the femoral head. It is wider at its base and projects anterior to the plane of the shaft. It is approximately 5 cm in length and forms an angle with the shaft of about 125 degrees. Its compact surface bone contains many nutrient foramina, with the compact bone being thickest on the inferior surface. The entire anterior surface of the neck and the proximal half of the posterior surface is within the capsular ligament.', 'Anatomy_img/N/3.png');
INSERT INTO `autobot` (`id`, `Name`, `Description`, `img_path`) VALUES
(127, 'Neck of the fibula', 'This is the narrowed region just below the head. Crossing the lateral surface of the neck is the common fibular (peroneal) nerve that is palpable at this point. With your fingers roll this nerve against the fibular neck and send a tingling sensation into your leg and foot.', 'Anatomy_img/E/N.png'),
(128, 'Neck of the scapula', 'The neck is just medial to the thick rim of bone around the glenoid cavity. It is a narrow constriction of the lateral angle that extends toward the base of the coracoid process and the spine.', 'Anatomy_img/N/5.png'),
(129, 'Neck of the radius', 'This is the constriction of the proximal radial shaft just distal to the expanded head.', 'Anatomy_img/N/6.png'),
(130, 'Neck of rib 1', 'The neck is the portion of bone that tapers proximally from the wider head. It terminates distally as the prominent tubercle. The neck is usually slightly rough and perforated by many small foramina. Various ligaments anchor from this portion of the rib to the adjacent vertebrae and ribs. The neck of the first rib is long and angled sharply from the rest of the bone.', 'Anatomy_img/N/7.png'),
(131, 'Neck of rib 2', 'The neck is the portion of bone that tapers proximally from the wider head. It ends distally as the prominent tubercle. The neck is usually slightly rough and perforated by many small foramina. Various ligaments anchor from this portion of the rib to the adjacent vertebrae and ribs.', 'Anatomy_img/N/8.png'),
(132, 'Neck of rib 3', 'The neck is the portion of bone that tapers proximally from the wider head. It ends distally as the prominent tubercle. The neck is usually slightly rough and perforated by many small foramina. Various ligaments anchor from this portion of the rib to the adjacent vertebrae and ribs.', 'Anatomy_img/N/9.png'),
(133, 'Neck of rib 4', 'The neck is the portion of bone that tapers proximally from the wider head. It ends distally as the prominent tubercle. The neck is usually slightly rough and perforated by many small foramina. Various ligaments anchor from this portion of the rib to the adjacent vertebrae and ribs.', 'Anatomy_img/N/10.png'),
(134, 'Optic disc', 'The optic disc is the point at which the optic nerve connects to the retina. The optic disc is commonly called the “blind spot” because it is the only part of the surface of the retina that is insensitive to light. It is located 3 millimeters to the nasal side of the macula. The circumference of the optic disk is slightly raised to form an eminence. There is also a central depression called the optic cup.', 'Anatomy_img/O/1.png'),
(135, 'Os coxae', 'These elements are the ilium, ischium, and pubis. In more primitive vertebrates these three elements are distinguished as three distinct bones. Over phylogenetic time they fuse to form the single os coxa. The junction of the bones occurs in the joint socket, the acetabulum. The united os coxae and sacrum form the pelvic girdle, uniting the posterior limbs to the axial skeleton. In general, the bone is composed two plates of compact bone with an internal core of spongy bone. In some thin areas of the bone, the inner spongy bone is absent and there exists only a thin plate of compact bone. In other areas where the bone is thick, dense compact buttresses are formed for additional strength. The details of the bone will be described with each of its elemental parts.', 'Anatomy_img/O/2.png'),
(136, 'Obturator crest', 'This sharp ridge-like crest faces anterolaterally on the external surface of the superior ramus. It serves as the upper border of the obturator foramen and provides attachment for the obturator membrane.', 'Anatomy_img/O/3.png'),
(137, 'Obturator sulcus', 'The obturator sulcus or groove is a notch in the superior border of the obturator foramen that allows passage between the true pelvis internal to the obturator foramen and the thigh externally. Through this opening pass the obturator vessels and nerve.', 'Anatomy_img/O/4.png'),
(138, 'Obturator foramen', 'This opening between pubic and ischial elements is positioned anteroinferior to the acetabulum. Its borders are the superior ramus of the pubis superiorly, the body and inferior ramus of the pubis medially, the ischial ramus inferiorly, and the body of the ischium laterally. A ligamentous membrane occludes the opening attaching around its margin, except superiorly where a small semilunar gap allows for communication between the pelvis and thigh. The foramen is larger in males than in females having an oval form and triangular form, respectively.', 'Anatomy_img/O/5.png'),
(139, 'Obturator membrane', 'The obturator membrane is the strong fibrous membrane that spans across the obturator foramen. It is perforated superiorly by the obturator canal, which transmits the obturator vessels and nerves into the medial compartment of the thigh. It also provides attachment surface for the internal and external obturator muscles.', 'Anatomy_img/O/6.png'),
(140, 'Olecranon fossa', 'In the extended position this concavity, on the posterior side of the distal humerus, receives the olecranon process.', 'Anatomy_img/O/7.png'),
(141, 'Olecranon', 'This forms the knob-like projection at the proximodorsal end of the bone. Elbow is the lay term for this process. It provides attachment to the aponeurotic tendon of the triceps brachii muscle.', 'Anatomy_img/O/8.png'),
(142, 'Oblique line of the radius', 'This is a ridge-like line coursing from the distolateral aspect of the tuberosity to the lateral border of the mid-radial shaft. It provides attachment to the radial head of the flexor digitorum superficialis.', 'Anatomy_img/O/9.png'),
(143, 'Orbital plate', 'This is the horizontal portion of the frontal bone forming the roofs of the orbits. It is a thin plate of bone, especially medially where it can be translucent. Its orbital surface is smooth, while its cranial surface is smooth to corrugate. The corrugations are impressions formed by the gyri of the frontal lobe of the brain.', 'Anatomy_img/O/10.png'),
(144, 'Peroneal trochlea', 'Located on the distal third of the lateral surface of the calcaneus this variable sized projection serves as the pulley-like prominence around which the peroneus longus and brevis tendons course as they pass distally into the foot. It is palpable approximately 2 centimeters inferior to the fibular malleolus.', 'Anatomy_img/P/1.png'),
(145, 'Posterior talar articular surface', 'The posterior talar articular surface is large and of an oval or oblong form. It articulates with the corresponding facet on the upper surface of the calcaneus, and is deeply concave in the direction of its long axis which runs forward and laterally at an angle of about 45⁰ with the median plane of the body.', 'Anatomy_img/P/2.png'),
(146, 'Proximal phalanges - foot', 'The longest of the phalangeal series, these bones have wide bases, thin, quadrilateral shafts, and expanded heads. The base is concave proximally for articulation with the metatarsal head, while the head is trochlear for the hinge-like articulation with the middle phalanx. They have shallow depressions on the lateral and medial sides of the head for the attachment of ligaments.', 'Anatomy_img/P/3.png'),
(147, 'Patella', 'This bone is of the sesamoid variety, meaning a bone that forms within a tendon. It is the largest of the sesamoid bones. The patella is positioned in the posterior half of the quadriceps tendon just anterior to the knee joint. It is a flattened bone with a curved superior margin and a triangular inferior border. An indistinct vertical ridge separates the posterior articular surface into medial and lateral articular surfaces, the lateral articular facet being larger than the medial articular facet. The anterior face of the bone is rough for attachment of the quadriceps tendon. The bone consists of a thin plate of compact bone covering a dense trabecular network of spongy bone.', 'Anatomy_img/P/4.png'),
(148, 'Posterior superior spine', 'This is the blunt posterior projecting end of the iliac crest. The landmark serves as the attachment surface for the oblique fibers of the dorsal sacroiliac ligament and the multifidus muscle.', 'Anatomy_img/P/5.png'),
(149, 'Posterior inferior spine', 'This landmark is a blunt posterior projection from the posterior iliac margin corresponding to the posterior angle of the auricular surface. It is separated from its superior counterpart by a shallow notch. This projection of bone provides attachment for sacroiliac ligaments.', 'Anatomy_img/P/6.png'),
(150, 'Posterior gluteal line', 'This line on the external surface of the iliac ala is the shortest of the three gluteal lines. It begins near the posterior limit of the iliac crest and courses inferiorly to the posterior inferior iliac spine. Anterior to this line is the posterior limit of the gluteus medius muscle, while posterior to this is the roughened surface for the iliac attachment of the gluteus maximus muscle.', 'Anatomy_img/P/7.png'),
(151, 'Posterior obturator tubercle', 'A small bump on the medial border of the ischial body anterior to the acetabular notch. To this bump attaches the superior ligamentous band of the obturator membrane. Above this band is the obturator sulcus.', 'Anatomy_img/P/8.png'),
(152, 'Pubis', 'It, like the ischium, has the form of an arch or U shape that when joined with the ischium forms the obturator foramen. The pubis consists of a thick, medially positioned body that articulates with the opposite pubic body. From the body are two laterally projecting rami, one superior to the other.', 'Anatomy_img/P/9.png'),
(153, 'Pubic tubercle', 'This is a rounded elevation projecting ventrally from the lateral end of the pubic crest. It provides attachment to the inguinal ligament and the inferior crus of the superficial inguinal ring.', 'Anatomy_img/P/10.png'),
(154, 'Quadrate tubercle', 'The quadrate reference is to the square shaped quadratus femoris muscle which attaches to this protuberance. This is a small rounded projection on the middle portion of the intertrochanteric crest.', 'Anatomy_img/Q/1.png'),
(155, 'Quadrate lobe of liver', 'The quadrate lobe is found on the inferior surface of the right lobe, between the umbilical fissure and the gallbladder fossa. It extends from the anterior border of the liver to the porta hepatis. It is in relation with the pyloric end of the stomach and the first part of the duodenum.', 'Anatomy_img/Q/2.png'),
(156, 'Quadriceps femoris', 'The Quadriceps femoris musculature is muscle group that share a common tendon of insertion via the patella to the tibial tuberosity. This large, powerful group of muscles forms the majority of the anterior compartment of the thigh. It is subdivided into separate portions, which have received distinctive names. One occupying the middle of the thigh, and connected above with the ilium, is called from its straight course the rectus femoris. The other three lie in immediate connection with the body of the femur, which they cover from the trochanters to the condyles. The portion on the lateral side of the femur is termed the vastus lateralis; that covering the medial side, the vastus medialis; and that in front, the vastus intermedius.', 'Anatomy_img/Q/3.png'),
(157, 'Quadriceps tendon', 'The quadriceps tendon is compound tendon formed by the junction of the rectus femoris, vastus lateralis, vastus intermedius, and vastus medialis muscles. This strong tendon, second only in size to the tendocalcaneus, arises above the patella as the four muscles of the quadriceps converge in a broad aponeurosis to engulf the sesamoid patella. After attaching to and surrounding all but the posterior articular surface of the patella, the tendon continues below the patella as a strong, thick band to insert into the tibial tuberosity. The portion of the tendon between the patella and the tibial tuberosity is named the patellar ligament.', 'Anatomy_img/Q/4.png'),
(158, 'Quadrate ligament', 'This is a thin, square-shaped ligament that covers the synovial membrane below the annular ligament. It is basically the fibrous capsule over this part of the synovial joint.', 'Anatomy_img/Q/5.png'),
(159, 'Retina', 'The retina is a delicate nervous membrane that lines the inner surface of the eye. Images of external objects are received on the retina. The optic nerve then sends nerve impulses from these images to various visual centers of the brain. Photoreceptor cells are directly sensitive to light. Its outer surface is in contact with the choroid. Its inner surface is in contact with the hyaloid membrane of the vitreous body.', 'Anatomy_img/R/1.png'),
(160, 'Ramus of the ischium', 'This term describes the slender, branch-like, anteroinferior projecting arm of the U-shaped ischium. This ramus joins the inferior ramus of the pubis forming the combined ischiopubic ramus. The ramus has an external or anterior surface that provides attachment for the obturator externus and part of the adductor magnus muscle. Its internal or posterior surface contributes to the lateral wall of the pelvis and perineum. The ramus has two borders, lateral and medial. The lateral border forms a sharp edge that contributes to the margin of the obturator foramen. The medial border is thick, rough and rounded. This border provides attachment for the superficial perineal fascia, the inferior fascia of the urogenital diaphragm, the transversus perinei profundus muscle, the posterior portion of the crus of the penis or clitoris, and the ischiocavernosus muscle.', 'Anatomy_img/R/2.png'),
(161, 'Radial fossa', 'This fossa is the radial fossa because it receives the head of the radius when the elbow is in full flexion. It is a small, shallow fossa positioned medial and superior to the capitulum.', 'Anatomy_img/R/3.png'),
(162, 'Radial notch', 'This smooth oval surface at the distolateral base of the trochlear notch forms a shallow concavity for articulation with the wheel-like sides of the radial head. These surfaces form the pivot joint responsible for the actions of pronation and supination.', 'Anatomy_img/R/4.png'),
(163, 'Radius', 'The radius is the lateral, slender, rod-like bone of the antebrachium. The rod-like shaft expands at both ends. The proximal end forms a wheel-like head with a proximal concavity, while the distal end expands medially to laterally to form the widest measure of the bone This end is concave anteriorly and convex and grooved posteriorly. Its ridge-like borders give it a triangular shape in cross section.', 'Anatomy_img/R/5.png'),
(164, 'Radial tuberosity', 'The tuberosity of the radius is the roughened projection of the anteromedial shaft just below the neck. It is the insertion site for the biceps brachii muscle.', 'Anatomy_img/R/6.png'),
(165, 'Rib 1', 'Ribs are long, slender flat bones. They fall under the classification of flat bone rather than long bone because they do not have an epiphysis with a medullary cavity. The bone consists of an outer shell of compact bone with a trabecular center. The rib has a bow-like shape. The first rib is the shortest of the ribs. It is distinguishable from the other ribs in being flat in the horizontal plane. The proximal aspect of the rib has more character than the distal aspect of the rib. The proximal end forms a ridged head with a single articular surface for the vertebral body. Just distal to the head is a long, tapered neck region that has a prominent tubercle projecting dorsally from its base. Just beyond the neck the rib angles sharply acquiring a flatter profile. This long, flat, gently arching portion of the rib is the costal body. The dorsal surface is rough and has two groove-like impressions for the subclavian vessels. The ventral surface is smooth. The body ends simply, forming a flattened end with a rough, oval surface for the attachment of the costal cartilage. This rib is one of the true ribs or vertebrosternal ribs. It receives this name because the costal cartilage unites the rib directly to the sternum.', 'Anatomy_img/R/7.png'),
(166, 'Rib 2', 'Ribs are long, slender flat bones. They fall under the classification of flat bone rather than long bone because they do not have an epiphysis with a medullary cavity. The bone consists of an outer shell of compact bone with a trabecular center. It has a bow-like shape. The second rib is intermediate in shape to the first rib and the central ribs. It is not as strongly arched as the first rib, but more so than the others. It is approximately twice the length of the first rib. The proximal aspect of the rib has more character than the distal aspect of the rib. Proximally, it forms a ridged head with articular surfaces for the vertebral body. Just distal to the head is a tapered neck region that has a prominent tubercle projecting posterolaterally from its base. Just beyond the neck the rib angles sharply acquiring a flatter profile. This long, flat, gently arching portion of the rib is the costal body. Beginning on the angle of the rib and continuing onto the proximal two-thirds of its body is a noticeable groove. This groove is the distinguishing landmark for the ventral surface of the rib. The body ends simply, forming a flattened end with a rough, oval surface for the attachment of the costal cartilage. This rib is one of the true ribs or vertebrosternal ribs. It receives this name because the costal cartilage unites the rib directly to the sternum.', 'Anatomy_img/E/8.png'),
(167, 'Rib 3', 'Ribs are long, slender flat bones. They fall under the classification of flat bone rather than long bone because they do not have an epiphysis with a medullary cavity. The bone consists of an outer shell of compact bone with a trabecular center. It has a bow-like shape. The proximal aspect of the rib has more character than the distal aspect of the rib. Proximally, it forms a ridged head with articular surfaces for the vertebral body. Just distal to the head is a tapered neck region that has a prominent tubercle projecting posterolaterally from its base. Just beyond the neck the rib angles sharply acquiring a flatter profile. This long, flat, gently arching portion of the rib is the costal body. Beginning on the angle of the rib and continuing onto the proximal two-thirds of its body is a noticeable groove. This groove is the distinguishing landmark for the ventral surface of the rib. The body ends simply, forming a flattened end with a rough, oval surface for the attachment of the costal cartilage. This rib is one of the true ribs or vertebrosternal ribs. It receives this name because the costal cartilage unites the rib directly to the sternum.', 'Anatomy_img/E/9.png'),
(168, 'Rib 4', 'Ribs are long, slender flat bones. They fall under the classification of flat bone rather than long bone because they do not have an epiphysis with a medullary cavity. The bone consists of an outer shell of compact bone with a trabecular center. It has a bow-like shape. The proximal aspect of the rib has more character than the distal aspect of the rib. Proximally, it forms a ridged head with articular surfaces for the vertebral body. Just distal to the head is a tapered neck region that has a prominent tubercle projecting posterolaterally from its base. Just beyond the neck the rib angles sharply acquiring a flatter profile. This long, flat, gently arching portion of the rib is the costal body. Beginning on the angle of the rib and continuing onto the proximal two-thirds of its body is a noticeable groove. This groove is the distinguishing landmark for the ventral surface of the rib. The body ends simply, forming a flattened end with a rough, oval surface for the attachment of the costal cartilage. This rib is one of the true ribs or vertebrosternal ribs. It receives this name because the costal cartilage unites the rib directly to the sternum.', 'Anatomy_img/R/10.png'),
(169, 'Sulcus calcanei', 'Rough groove on the superior surface of the calcaneus between the posterior and middle articular surfaces for the talus. This groove, when articulated with the talus, forms the floor of the sinus tarsi that contains the talocalcanean and cervical interosseous ligaments.', 'Anatomy_img/S/1.png'),
(170, 'Sustentaculum tali', 'This is the lateral, shelf-like projection of bone that supports the talus. Its superior surface is covered by the smooth oval middle articular surface for the talus.', 'Anatomy_img/S/2.png'),
(171, 'Sulcus tali', 'This sulcus is the deep, roughened groove on the inferior surface of the talus between the posterior and middle articular surfaces for the calcaneus. Many large nutrient foramina perforate the bone of this groove. When the talus is articulated with the calcaneus this groove forms the roof of the sinus tarsi that contains talocalcanean and cervical interosseous ligaments.', 'Anatomy_img/S/3.png'),
(172, 'Shaft or body of metatarsal', 'The shaft forms the central portion or body of the bone. The shaft is thick and prismatic in shape. It has a longitudinally concave plantar surface for the attachment of interosseous muscles.', 'Anatomy_img/S/4.png'),
(173, 'Sesamoid bones of metatarsal 1', 'These small bones arise as compression struts in the split tendon of the flexor hallucis brevis muscle. They sit on the grooved plantar facets at the head end of the bone.', 'Anatomy_img/S/5.png'),
(174, 'Shaft or body of metatarsal 2', 'The shaft forms the central portion or body of the bone. It has a longitudinally concave plantar surface for the attachment of interosseous muscles.', 'Anatomy_img/S/6.png'),
(175, 'Sclera', 'The sclera is the white of the eyes. It is a portion of the fibrous tunic of the eye and is composed of dense irregular collagenous connective tissue. It is the protective outer layer of the eye.', 'Anatomy_img/S/7.png'),
(176, 'Shaft or body of metatarsal 3', 'The shaft forms the central portion or body of the bone. It has a longitudinally concave plantar surface for the attachment of interosseous muscles.', 'Anatomy_img/S/8.png'),
(177, 'Shaft or body of metatarsal 4', 'The shaft forms the central portion or body of the bone. It has a longitudinally concave plantar surface for the attachment of interosseous muscles.', 'Anatomy_img/S/9.png'),
(178, 'Shaft or body of metatarsal 5', 'The shaft forms the central portion or body of the bone. It has a longitudinally concave plantar surface for the attachment of interosseous muscles.', 'Anatomy_img/S/10.png'),
(179, 'Tarsal sinus', 'The sinus tarsi is an oblique groove that crosses the plantar surface of the talus and the dorsal surface of the calcaneus. It contains ligaments and transmits vessels deep through the tarsal region of the foot.', 'Anatomy_img/T/1.png'),
(180, 'Talus', 'The talus is the second largest and most proximal tarsal bone. It consists of a cuboid body, a distally directed neck capped by a convex, oval head, a proximolateral facet for the fibular malleolus, and a proximal trochlea for the tibia.', 'Anatomy_img/T/2.png'),
(181, 'Trochlea of the talus', 'The proximal articular surface of the talus resembles a pulley wheel. This smooth, grooved surface forms the articular face for the distal end of the tibia.', 'Anatomy_img/T/3.png'),
(182, 'Tuberosity of the navicular', 'This is the roughened projection on the medial aspect of the navicular bone. It serves as the primary attachment site for the tibialis posterior muscle, while a small groove just lateral to the tuberosity transmits the remainder of the tendon to the cuneiform and metatarsal attachments.', 'Anatomy_img/T/4.png'),
(183, 'Tuberosity of the cuboid', 'The cuboid tuberosity is a rough ridge of bone that courses obliquely across the plantar surface of the bone from proximolaterally to distomedially. At its distal extremity it forms a small laterally projecting articular facet for a sesamoid bone in the tendon of the peroneus longus. To this ridge are attached fibers of the long plantar ligament.', 'Anatomy_img/T/5.png'),
(184, 'Tuberosity of metatarsal 1', 'This is a prominent bump at the proximal end of the bone. It sits laterally on the plantar surface and provides attachment for ligaments.', 'Anatomy_img/T/6.png'),
(185, 'Tragus', 'The tragus is the small flap at the anterior boundary of the concha that projects backward over the meatal opening. It often has course hairs on its tip, especially in older men.', 'Anatomy_img/T/7.png'),
(186, 'Tuberosity of metatarsal 5', 'The tuberosity forms a rough projection at the proximolateral aspect of the bone. This is easily palpable on the lateral aspect of the ball of the foot.', 'Anatomy_img/T/8.png'),
(187, 'Tuberosity of the distal phalanges ...', 'The tuberosity is the rough surface on the distal plantar surface of the bone. This surface provides attachment for the soft mass of the finger tips.', 'Anatomy_img/T/9.png'),
(188, 'Tubercle of the ilium', 'This is a rounded projection of the external iliac crest. Its location is about five centimeters onto the crest from its anterior end.', 'Anatomy_img/T/10.png'),
(189, 'Upper limb - bones of', 'The proximal end of the superior appendage, the clavicle and scapula, is the pectoral or shoulder girdle. This girdle of bones provides a broad base of support and through muscles, rather than ligaments, helps anchor the limb to the axial skeleton. The humerus forms the skeletal framework for the next region of the appendage, the brachium. Distal to the brachium is the antebrachium containing the radius and ulna. The distal most region of the superior limb is the hand consisting of a eight carpal bones, five metacarpal bones, and fourteen phalanges.', 'Anatomy_img/U/1.png'),
(190, 'Ulna', 'The ulna is the medial and longer bone of the antebrachium. It is thick and notched at its proximal end having a hook-like appearance that tapers to a thin shaft ending distally as a small round head. The bone is triangular in cross section.', 'Anatomy_img/U/2.png'),
(191, 'Ulnar tuberosity', 'This roughened area of bone sits distomedially at the base of the coronoid process. It is the attachment site for the brachialis muscle.', 'Anatomy_img/U/3.png'),
(192, 'Ulnar notch', 'This is a smooth, concave notch formed on the distomedial surface. It is covered with articular cartilage serving as the articular receptacle for the head of the ulna. The articular disc for the inferior radio-ulnar joint attaches to a ridge at the distal edge of the notch.', 'Anatomy_img/U/4.png'),
(193, 'Uncinate process', 'Descending posteriorly and inferiorly from the labyrinth is a thin hook-like process that projects toward the maxillary hiatus. In the opening of the hiatus it articulates with the ethmoidal process of the inferior nasal concha. It forms the inferior boundary of the semilunar hiatus that arches from the anterior ethmoidal sinuses into the middle meatus.', 'Anatomy_img/U/5.png'),
(194, 'Ulnar nerve', 'The ulnar nerve arises from the medial cord of the brachial plexus in common with the medial head of the median. It lies upon the medial side of the third portion of the axillary artery, between it and the axillary vein. It then passes down the medial side of the arm upon the medial surface of the triceps, piercing the medial intermuscular septum together with the superior ulnar collateral artery at the distal third of the arm to reach the space between the medial epicondyle and the olecranon.', 'Anatomy_img/U/6.png'),
(195, 'Ulnar artery', 'The ulnar artery is larger than the radial. It is the other terminal branch of the brachial artery. It curves toward the ulnar side of the forearm, which it reaches at the junction of the proximal and middle thirds of the forearm. After this, it skirts the ulnar border of the forearm to the wrist. A line drawn with its convexity toward the ulnar side from a point one centimeter below the middle of the bend of the elbow to the junction of the proximal with the middle third of the ulnar border of the forearm will represent the course of the proximal, or deep, portion of this vessel. A line drawn from a point midway between the medial epicondyle and the middle of the bend of the elbow to the radial side of the pisiform bone represents its course in the distal two-thirds of the forearm. It crosses the transverse carpal ligament on the radial side of the pisiform bone. It runs across the palm, forming the superficial palmar arch, which is usually completed by anastomosis with the superficial palmar artery. In its proximal half, the ulnar artery is deep, being covered by all of the superficial flexors except the flexor carpi ulnaris. In its distal half, it is more superficial, being overlapped by the tendon of the flexor carpi ulnaris. While immediately proximal to the wrist, it is subcutaneous and lies between the tendon of the flexor carpi ulnaris and the deepest tendon of the flexor digitorum superficialis. It lies upon the brachialis, the flexor digitorum profundus, and the transverse carpal ligament. It has two vena comites. In the proximal third of the course of the artery the ulnar nerve lies some distance to its ulnar side. Its branches in the forearm are: the anterior ulnar recurrent, the posterior ulnar recurrent, the common interosseous, and the muscular. The branches at the wrist are: the anterior and dorsal carpal. The branches in the hand are the deep palmer branch; it continues as the superficial palmar arch.', 'Anatomy_img/E/7.png'),
(196, 'Umbilical artery', 'The umbilical artery is the internal iliac after it passes through the umbilicus in the fetus. The umbilical arteries wind around the umbilical vein, helping to form the umbilical cord, and are distributed to the placenta. After the placental circulation has ceased, all but a short portion of the lower end of the hypogastric artery becomes obliterated and forms the lateral umbilical ligament. The proximal end becomes reduced in size and forms the root of the superior vesical artery within the abdominal cavity.', 'Anatomy_img/E/8.png'),
(197, 'Uterine artery', 'The uterine artery arises from the anterior division of the internal iliac artery just below or in common with the vaginal artery. It passes downward and medially on the levator ani toward the cervix. It crosses in front of the ureter one to one and a half centimeters from the cervix. It then turns upward and ascends in a twisted course between the layers of the broad ligament and on the side of the uterus. It sends numerous branches at a right angle to spread over both surfaces of the uterus in a winding way. It anastomoses with the uterine branch of the ovarian artery. The cervical branch of the uterine artery springs from that vessel as it crosses the ureter. It passes directly medially and divides into four or five branches. Some of these branches anastomose with branches of the vaginal to form the vaginal arteries. They run along the median line of the vaginal wall, one lying in front and the other behind.', 'Anatomy_img/E/9.png'),
(198, 'Ulnar vein', 'The ulnar veins run along the same course as the ulnar artery. The anterior ulnar vein passes proximally along the ulnar side of the forearm to within a short distance of the elbow, where it joins the posterior ulnar to form the common ulnar, which in turn almost immediately unites with the median cubital to form the basilic vein. It is formed by radicles at the wrist, and communicates with the median and posterior ulnar veins. The anterior ulnar vein passes to the front of the forearm just above the wrist, while the posterior ulnar continues on the back of the forearm almost as far as the elbow. These veins commence on the back of the hand in a plexus which receives the veins of the fingers, the cephalic vein arises from the lateral side, and the anterior and the basilic from the medial side of the plexus. The ulnar veins drain the medial aspect of the forearm.', 'Anatomy_img/U/10.png'),
(199, 'Vertebral column', 'These 33 segments form the 26 bones of the vertebral column. The bones are divisible into seven cervical vertebrae, twelve thoracic vertebrae, five lumbar vertebrae, and the fused sacrum and coccyx. The column supports the trunk and skull, protects the spinal cord, and provides attachment for muscles that move this flexible column.', 'Anatomy_img/V/1.png'),
(200, 'Vertebral foramen of cervical vertebra ...', 'This is the large opening in the center of the vertebra. The foramen is larger in this vertebra than any of its cervical counterparts. It is bounded anteriorly by the anterior arch, posteriorly by the posterior arch, and laterally by the two lateral masses. It houses the spinal cord and its meningeal coverings.', 'Anatomy_img/V/2.png'),
(201, 'Vertebral foramen of cervical vertebra ...', 'This is the large opening in the center of the vertebra. It is bounded anteriorly by the body of the vertebra. The posterior vertebral arch encompasses the remainder of its circumference. This large, triangular opening houses the spinal cord and its meningeal coverings.', 'Anatomy_img/V/3.png'),
(202, 'Vertebral body of cervical vertebra ...', 'The thick, rectangular body of the axis is unique in having a superior projection, the dens. The body is formed of a thin outer covering of compact bone surrounding an internal core of spongy or cancellous bone. Its flattened inferior surface receives the intervertebral disc that unites it with the subjacent vertebra.', 'Anatomy_img/V/4.png'),
(203, 'Vertebral foramen of cervical vertebra ...', 'This large foramen has a triangular shape. The foramen\'s borders are the long posterior side of the rectangular body anteriorly, the pedicles and articular pillars laterally, and the thin laminae posteriorly. It houses the spinal cord and its meningeal coverings.', 'Anatomy_img/V/5.png'),
(204, 'Vertebral body of cervical vertebra ...', 'The vertebral body is small and rectangular, being wider in the transverse plane. Anteriorly, its inferior margin forms a lip that projects inferiorly. The superior surface is concave in the transverse plane and forms projecting ridges at its lateral margins. The inferior surface is convex in this plane and has depressions laterally to receive the projecting margins from the next superior vertebra. The body has a thin covering of compact bone perforated by many foramina. The internal bony core is cancellous.', 'Anatomy_img/V/6.png'),
(205, 'Vertebral foramen of cervical vertebra ...', 'This large foramen has a triangular shape. The foramen\'s borders are the long posterior side of the rectangular body anteriorly, the pedicles and articular pillars laterally, and the thin laminae posteriorly. It houses the spinal cord and its meningeal coverings.', 'Anatomy_img/V/7.png'),
(206, 'Vertebral body of cervical vertebra ...', 'The vertebral body is small and rectangular, being wider in the transverse plane. Anteriorly, its inferior margin forms a lip that projects inferiorly. The superior surface is concave in the transverse plane and forms projecting ridges at its lateral margins. The inferior surface is convex in this plane and has depressions laterally to receive the projecting margins from the next superior vertebra. The body has a thin covering of compact bone perforated by many foramina. The internal bony core is cancellous.', 'Anatomy_img/V/8.png'),
(207, 'Vertebral foramen of cervical vertebra ...', 'This large foramen has a triangular shape. The foramen\'s borders are the long posterior side of the rectangular body anteriorly, the pedicles and articular pillars laterally, and the thin laminae posteriorly. It houses the spinal cord and its meningeal coverings.', 'Anatomy_img/V/9.png'),
(208, 'Vertebral body of cervical vertebra ...', 'The vertebral body is small and rectangular, being wider in the transverse plane. Anteriorly, its inferior margin forms a lip that projects inferiorly. The superior surface is concave in the transverse plane and forms projecting ridges at its lateral margins. The inferior surface is convex in this plane and has depressions laterally to receive the projecting margins from the next superior vertebra. The body has a thin covering of compact bone perforated by many foramina. The internal bony core is cancellous.', 'Anatomy_img/V/10.png'),
(209, 'White matter', 'The white matter of the neuraxis is clusters of cells that consist of neuritis. It is located in the brain and spinal cord.', 'Anatomy_img/W/1.png'),
(210, 'Wrist joint and ligaments', 'The mobile wrist joint, which occurs between the distal end of the radius and the proximal carpal bones is closely associated with the distal radio-ulnar joint. An articular disc separates the two joints into distinct synovial capsules.', 'Anatomy_img/W/2.png'),
(211, 'Wrist', '', 'Anatomy_img/W/3.png'),
(212, 'Xiphoid process', 'The xiphoid process is the smallest, most variable sternal segment. It can range from rounded to bifid. At its junction with the body it forms shallow demifacets that complete the lower half of the last costal notch. It often remains cartilaginous late into life and can be perforated by a foramen.', 'Anatomy_img/X/1.png'),
(213, 'Xiphisternal joint', 'The xiphisternal joint arises as a synchondrosis between the inferior sternebrae of the sternal body and the xiphoid process. It can remain until the middle years of life, but usually ossifies to form a synostosis between the two sternal elements.', 'Anatomy_img/X/2.png'),
(214, 'Zygomatic arch', 'The zygomatic arch is the bridge-like bar of bone that is comprised of the zygomatic process of the temporal bone and the zygomatic process of the zygomatic bone. It is a flattened bar of bone that provides attachment for the masseter muscle and forms the superficial boundary of the osseous tunnel for the temporalis tendon. It can be easily palpated as the horizontal ridge of bone projecting anteriorly from the tragus of the auricle.', 'Anatomy_img/Z/1.png'),
(215, 'Zygomatic process of frontal bone', 'This is the lateral thick projection of the supra-orbital margin. It forms the superolateral border of the orbit and its inferior surface forms a deep denticulate articulation with the zygomatic bone.', 'Anatomy_img/Z/2.png'),
(216, 'Zygomatic process of temporal bone', 'This is a thin arch-like process that originates from two roots on the anterolateral aspect of the squamous temporal bone. The posterior root of the arch originates as a ridge above the external acoustic meatus. Its anterior root originates medially from the articular tubercle. The posterior root continues as the superior margin of the process, while the anterior root continues as the inferior margin of the process. The anterior end of the process forms a rough, serrate suture that articulates with the zygomatic bone. The superior border of the process is the attachment site of the temporalis fascia, while the inferior border and medial surface provide attachment for the masseter muscle. This process can be easily palpated as the ridge of bone on the side of the face.', 'Anatomy_img/Z/3.png'),
(217, 'Zygomatic process of maxilla', 'This is a pyramid shaped process that projects laterally to form a rough articular surface with the zygomatic bone. Its three surfaces are the facial, infratemporal, and orbital. Its base is lateral and apex medial.', 'Anatomy_img/Z/4.png'),
(218, 'Zygomatic', 'This yoke-shaped bone has three distinct surfaces, five borders, and two processes. It is situated anterolateral on the face as the \"cheekbone,\" contributing to the lateral and inferior walls of the orbit. It consists of external and internal laminae of compact bone with an inner core of spongy bone.', 'Anatomy_img/Z/5.png'),
(219, 'Zygomatico-orbital foramen', 'This opening in the orbital surface of the bone can be single or paired. When one foramen is present the zygomatic vessels and nerve enter and then branch within the bone to exit different foramina as the zygomaticofacial and zygomaticotemporal vessels and nerve. If two foramina exist, the branching of the zygomatic occurs in the orbit before perforating the bone.', 'Anatomy_img/Z/6.png'),
(220, 'Zygomaticofacial foramen', 'This foramen sits on the anterolateral (cheek) surface just inferior to the orbital margin. It transmits the zygomaticofacial vessels and nerve. Sometimes it is doubled, one foramen transmitting the vessels, the other foramen the nerve.', 'Anatomy_img/Z/7.png'),
(221, 'Zygomaticotemporal foramen', 'This foramen opens onto the temporal surface of the bone near the base of the frontal process. It transmits the zygomaticotemporal vessels and nerve.', 'Anatomy_img/Z/8.png'),
(222, 'Zygomaticomaxillary suture', 'The zygomaticomaxillary suture is a thick, weakly serrate suture between the maxillary process of the zygomatic bone and the zygomatic process of the maxillary bone on the anterior surface of cheek region below the orbit.', 'Anatomy_img/Z/9.png'),
(223, 'Zygapophysial joints', 'The zygapophysial joints are intervertebral articulations between the two superior articular processes of a vertebra and the two inferior articular processes of the overlying vertebra. The cartilaginous surfaces of each joint are enclosed by an articular capsule, which is relaxed in the cervical and tense in the lower vertebral region. There are no accessory ligaments. The joint articular surfaces vary from region to region. In the cervical region they are planar and primarily situated in the transverse plane. In the thorax they are planar and situated in the frontal plane. The surfaces of the lumbar vertebrae are reciprocally curved, one surface being concave and the opposite convex. They are primarily situated in the sagittal plane.', 'Anatomy_img/Z/10.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `autobot`
--
ALTER TABLE `autobot`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `autobot`
--
ALTER TABLE `autobot`
  MODIFY `id` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=224;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
